package com.gym.code.model;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Course generated by hbm2java
 */
@Entity
@Table(name = "course", catalog = "gym")
public class Course implements java.io.Serializable {

	private Integer courseId;
	private String courseName;
	private String courseType;
	private Integer courseNum;
	private String courseTime;
	private String courseMoney;
	private String courseClass;

	public Course() {
	}

	public Course(String courseName, String courseType, Integer courseNum, String courseTime, String courseMoney,
			String courseClass) {
		this.courseName = courseName;
		this.courseType = courseType;
		this.courseNum = courseNum;
		this.courseTime = courseTime;
		this.courseMoney = courseMoney;
		this.courseClass = courseClass;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "course_id", unique = true, nullable = false)
	public Integer getCourseId() {
		return this.courseId;
	}

	public void setCourseId(Integer courseId) {
		this.courseId = courseId;
	}

	@Column(name = "course_name")
	public String getCourseName() {
		return this.courseName;
	}

	public void setCourseName(String courseName) {
		this.courseName = courseName;
	}

	@Column(name = "course_type")
	public String getCourseType() {
		return this.courseType;
	}

	public void setCourseType(String courseType) {
		this.courseType = courseType;
	}

	@Column(name = "course_num")
	public Integer getCourseNum() {
		return this.courseNum;
	}

	public void setCourseNum(Integer courseNum) {
		this.courseNum = courseNum;
	}

	@Column(name = "course_time")
	public String getCourseTime() {
		return this.courseTime;
	}

	public void setCourseTime(String courseTime) {
		this.courseTime = courseTime;
	}

	@Column(name = "course_money")
	public String getCourseMoney() {
		return this.courseMoney;
	}

	public void setCourseMoney(String courseMoney) {
		this.courseMoney = courseMoney;
	}

	@Column(name = "course_class")
	public String getCourseClass() {
		return this.courseClass;
	}

	public void setCourseClass(String courseClass) {
		this.courseClass = courseClass;
	}

}
