package com.gym.code.model;
// Generated 2018-6-19 18:41:17 by Hibernate Tools 4.0.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Givelessons generated by hbm2java
 */
@Entity
@Table(name = "givelessons", catalog = "gym")
public class Givelessons implements java.io.Serializable {

	private Integer givelessonsId;
	private Integer userId;
	private Integer courseId;

	public Givelessons() {
	}

	public Givelessons(Integer userId, Integer courseId) {
		this.userId = userId;
		this.courseId = courseId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "givelessons_id", unique = true, nullable = false)
	public Integer getGivelessonsId() {
		return this.givelessonsId;
	}

	public void setGivelessonsId(Integer givelessonsId) {
		this.givelessonsId = givelessonsId;
	}

	@Column(name = "user_id")
	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	@Column(name = "course_id")
	public Integer getCourseId() {
		return this.courseId;
	}

	public void setCourseId(Integer courseId) {
		this.courseId = courseId;
	}

}
