package com.gym.code.model;
// Generated 2018-6-12 10:00:57 by Hibernate Tools 4.0.1.Final

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Goods generated by hbm2java
 */
@Entity
@Table(name = "goods", catalog = "gym")
public class Goods implements java.io.Serializable {

	private Integer goodsId;
	private String goodsName;
	private Integer goodsIntegral;
	private Integer goodsNum;

	public Goods() {
	}

	public Goods(String goodsName, Integer goodsIntegral, Integer goodsNum) {
		this.goodsName = goodsName;
		this.goodsIntegral = goodsIntegral;
		this.goodsNum = goodsNum;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "goods_id", unique = true, nullable = false)
	public Integer getGoodsId() {
		return this.goodsId;
	}

	public void setGoodsId(Integer goodsId) {
		this.goodsId = goodsId;
	}

	@Column(name = "goods_name")
	public String getGoodsName() {
		return this.goodsName;
	}

	public void setGoodsName(String goodsName) {
		this.goodsName = goodsName;
	}

	@Column(name = "goods_integral")
	public Integer getGoodsIntegral() {
		return this.goodsIntegral;
	}

	public void setGoodsIntegral(Integer goodsIntegral) {
		this.goodsIntegral = goodsIntegral;
	}

	@Column(name = "goods_num")
	public Integer getGoodsNum() {
		return this.goodsNum;
	}

	public void setGoodsNum(Integer goodsNum) {
		this.goodsNum = goodsNum;
	}

}
