package com.gym.code.model;
// Generated 2018-6-12 10:00:57 by Hibernate Tools 4.0.1.Final

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Integral generated by hbm2java
 */
@Entity
@Table(name = "integral", catalog = "gym")
public class Integral implements java.io.Serializable {

	private Integer integralId;
	private Integer integralNum;
	private Integer userId;

	public Integral() {
	}

	public Integral(Integer integralNum, Integer userId) {
		this.integralNum = integralNum;
		this.userId = userId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "integral_id", unique = true, nullable = false)
	public Integer getIntegralId() {
		return this.integralId;
	}

	public void setIntegralId(Integer integralId) {
		this.integralId = integralId;
	}

	@Column(name = "integral_num")
	public Integer getIntegralNum() {
		return this.integralNum;
	}

	public void setIntegralNum(Integer integralNum) {
		this.integralNum = integralNum;
	}

	@Column(name = "user_id")
	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

}
