package com.gym.code.model;
// Generated 2018-6-12 10:00:57 by Hibernate Tools 4.0.1.Final

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Machanism generated by hbm2java
 */
@Entity
@Table(name = "machanism", catalog = "gym")
public class Machanism implements java.io.Serializable {

	private Integer machanismId;
	private String machanismName;
	private String machanismMoney;
	private Integer machanismNum;
	private Integer userId;

	public Machanism() {
	}

	public Machanism(String machanismName, String machanismMoney, Integer machanismNum, Integer userId) {
		this.machanismName = machanismName;
		this.machanismMoney = machanismMoney;
		this.machanismNum = machanismNum;
		this.userId = userId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "machanism_id", unique = true, nullable = false)
	public Integer getMachanismId() {
		return this.machanismId;
	}

	public void setMachanismId(Integer machanismId) {
		this.machanismId = machanismId;
	}

	@Column(name = "machanism_name")
	public String getMachanismName() {
		return this.machanismName;
	}

	public void setMachanismName(String machanismName) {
		this.machanismName = machanismName;
	}

	@Column(name = "machanism_money")
	public String getMachanismMoney() {
		return this.machanismMoney;
	}

	public void setMachanismMoney(String machanismMoney) {
		this.machanismMoney = machanismMoney;
	}

	@Column(name = "machanism_num")
	public Integer getMachanismNum() {
		return this.machanismNum;
	}

	public void setMachanismNum(Integer machanismNum) {
		this.machanismNum = machanismNum;
	}

	@Column(name = "user_id")
	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

}
