package com.gym.code.model;
// Generated 2018-6-12 10:00:57 by Hibernate Tools 4.0.1.Final

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Pay generated by hbm2java
 */
@Entity
@Table(name = "pay", catalog = "gym")
public class Pay implements java.io.Serializable {

	private Integer payId;
	private Integer userId;
	private Integer courseId;

	public Pay() {
	}

	public Pay(Integer userId, Integer courseId) {
		this.userId = userId;
		this.courseId = courseId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "pay_id", unique = true, nullable = false)
	public Integer getPayId() {
		return this.payId;
	}

	public void setPayId(Integer payId) {
		this.payId = payId;
	}

	@Column(name = "user_id")
	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	@Column(name = "course_id")
	public Integer getCourseId() {
		return this.courseId;
	}

	public void setCourseId(Integer courseId) {
		this.courseId = courseId;
	}

}
