package com.gym.code.model;
// Generated 2018-6-13 15:58:50 by Hibernate Tools 4.0.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "user", catalog = "gym")
public class User implements java.io.Serializable {

	private Integer userId;
	private String username;
	private String password;
	private String name;
	private String sex;
	private Integer age;
	private String tel;
	private String money;
	private String identity;
	private String cardtime;
	private String cardlengthtime;
	private String prelogintime;

	public User() {
	}

	public User(String username, String password, String name, String sex, Integer age, String tel, String money,
			String identity, String cardtime, String cardlengthtime, String prelogintime) {
		this.username = username;
		this.password = password;
		this.name = name;
		this.sex = sex;
		this.age = age;
		this.tel = tel;
		this.money = money;
		this.identity = identity;
		this.cardtime = cardtime;
		this.cardlengthtime = cardlengthtime;
		this.prelogintime = prelogintime;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "user_id", unique = true, nullable = false)
	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	@Column(name = "username")
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "password")
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "sex")
	public String getSex() {
		return this.sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	@Column(name = "age")
	public Integer getAge() {
		return this.age;
	}

	public void setAge(Integer age) {
		this.age = age;
	}

	@Column(name = "tel")
	public String getTel() {
		return this.tel;
	}

	public void setTel(String tel) {
		this.tel = tel;
	}

	@Column(name = "money")
	public String getMoney() {
		return this.money;
	}

	public void setMoney(String money) {
		this.money = money;
	}

	@Column(name = "identity")
	public String getIdentity() {
		return this.identity;
	}

	public void setIdentity(String identity) {
		this.identity = identity;
	}

	@Column(name = "cardtime")
	public String getCardtime() {
		return this.cardtime;
	}

	public void setCardtime(String cardtime) {
		this.cardtime = cardtime;
	}

	@Column(name = "cardlengthtime")
	public String getCardlengthtime() {
		return this.cardlengthtime;
	}

	public void setCardlengthtime(String cardlengthtime) {
		this.cardlengthtime = cardlengthtime;
	}

	@Column(name = "prelogintime")
	public String getPrelogintime() {
		return this.prelogintime;
	}

	public void setPrelogintime(String prelogintime) {
		this.prelogintime = prelogintime;
	}

}
